#!/usr/bin/env expect

set timeout 30
proc abort {} { exit 2 }

spawn openssl s_client -connect mail.dev.gee-zone.us:587 -starttls smtp -quiet
expect default abort "250 "
send "HELO utility.dev.gee-zone.us\r"
expect default abort "\n250 "
send "AUTH PLAIN\r"
expect default abort "\n334"
send "AGRpYWxsb2dAZGV2LmdlZS16b25lLnVzAHRoaXNpc2F0ZXN0MDAx\r"
expect default abort "\n235 "
send "MAIL FROM:diallog@dev.gee-zone.us\r"
expect default abort "\n250 "
send "RCPT TO:clannister@got.gee-zone.us\r"
expect default abort "\n250 "
send "DATA\r"
expect default abort "\n354 "
send "From: diallog@dev.gee-zone.us\r"
send "To: clannister@got.gee-zone.us\r"
send "Subject: Test\r"
send "\r"
send "Testing\r"
send ".\r"
expect default abort "\n250 "
send "QUIT\r"
